import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  button: {
    marginTop: 10,
    flex: 1,
    backgroundColor: '#d06f3b',
    width: '50%',
    borderRadius: 20,
    left: 100,
  },
  buttonText: {
    color: '#e9e7e4',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  inline: {
    flex: 1,
    flexDirection: 'row',
    width: '70%',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  carousel: {
    zIndex: 1,
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#e9e7e4',
  },
  card: {
    marginLeft: '5%',
    marginTop: '5%',
    aspectRatio: 2.5 / 3.5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '50%',
  },
  cardCap: {
    marginLeft: '5%',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    height: 20,
    width: '50%',
    backgroundColor: '#d06f3b',
  },
  details: {
    marginTop: '15%',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    right: '11%',
  },
  pfp: {
    aspectRatio: 1 / 1,
    height: '45%',
    borderRadius: 500,
    borderColor: '#54130e',
    borderWidth: 2,
  },
  smallPfp: {
    zIndex: 1,
    aspectRatio: 1 / 1,
    borderRadius: 500,
    borderColor: '#54130e',
    borderWidth: 1,
  },
  typeText: {
    color: '#e9e7e4',
    left: '10%',
    fontSize: 20,
    fontWeight: 'bold',
    top: '7%',
  },
  spaceEvenly: {
    flex: 1,
    justifyContent: 'space-between',
  },
  offer: {
    flex: 1,
    flexDirection: 'column',
    margin: 10,
    marginBottom: 0,
  },
  offerCard: {
    flex: 1,
    flexDirection: 'row',
    height: 90,
  },
  offerDetails: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#a6502c',
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    width: '50%',
    height: '70%',
    top: '10%',
    right: '5%',
  },
  offerText: {
    color: '#e9e7e4',
    width: '60%',
    left: '8%',
    fontSize: 18,
    top: '4%',
  },
  miniCard: {
    height: '100%',
    aspectRatio: 2.5 / 3.5,
    marginLeft: 10,
    borderColor: '#54130e',
    borderWidth: 1,
    borderRadius: 4,
  },
  hidden: {
    height: 0,
  },
});
